version: "1"

services:
  frontend:
    build: ./react
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build: ./node
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
